josipcodes/hack-team-2

README.md
assets/js/script.js
index.html

I've tested these pages and the CSS and Javascript files are both linked and work properly with the index.html file.

Create and link html, css and javascript pages. Create images folder.

---

README.md

Added the CI hackathon readme template

Add readme template

---

Procfile
project_pride/settings.py
requirements.txt

Ready for deployment

---

about/urls.py
about/views.py
blog/urls.py
blog/views.py
history/urls.py
history/views.py
project_pride/settings.py
project_pride/urls.py
templates/base.html

Updated urls for each app

---

project_pride/urls.py

fixed about thingy

---

README.md

updated the context and created dropdowns

Fix dropdowns update context

---

templates/base.html

updated base.html for cards app

---

project_pride/settings.py

updated settings with Cloudinary connections

---

project_pride/settings.py
project_pride/urls.py
requirements.txt

Heroku app not working, trying to troubleshoot and fix it.

Troubleshoot Heroku app

---

about/views.py
blog/views.py
cards/views.py
history/views.py

fiexed views for new .html locations

---

templates/index.html

added news ticker, needs some styling

---

history/templates/history/history.html
static/css/style.css

Prideflag css on History timeline (hopefully)

css changes to history timeline to add prideflag colours

---

project_pride/settings.py

mongo test

---

blog/templates/blog/blog.html
static/css/style.css

Expand the latest blog post, add image overlay

Style blog list

---

blog/templates/blog/blog.html

Refactor blog code

---

templates/base.html

added favicon

---

contact/templates/contact/contact.html
contact/templates/contact/emails/contactform.html
static/css/style.css

Preliminary styling for Contact Form

Preliminary css for contact form

---

contact/templates/contact/contact.html
static/css/style.css

Styling for Contact Form

---

staticfiles/css/style.css

css changes to history timeline

---

README.md

First draft of resources table. I can add new sources from here.

Updated Readme with credits

---

static/css/style.css

Add media queries to contact form

Add media queries to contact form

---

README.md

Added all resources I could find in Miro, Google Doc and the Rainbow cards + any that were send to me directly.

UPDATED Readme with sources and removed few typos

---

README.md

Quick fixes around the team contact details

ADDED team contact details to READme

---

README.md

updated acknowledgements and some typo's.

Change Acknowledgements

---

blog/templates/blog/blog_post.html
static/css/blog.css
staticfiles/css/blog.css

Update image display on blog post
